# Generated by Django 4.1.3 on 2022-11-07 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploaddrs", options={"verbose_name_plural": "Upload DRS."},
        ),
        migrations.CreateModel(
            name="GenerateDrs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drs_number", models.BigIntegerField()),
                ("load_number", models.CharField(max_length=200)),
                ("drs_date", models.DateTimeField()),
                ("c_note_numbetr", models.BigIntegerField()),
                ("from_center", models.CharField(max_length=256)),
                ("receiver", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.routemaster",
                    ),
                ),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.deliveryboy",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.bookingtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Generate DRS",},
        ),
    ]
