# Generated by Django 4.1.3 on 2022-11-07 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0002_alter_uploaddrs_options_generatedrs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_note_number", models.BigIntegerField()),
                ("from_destination", models.CharField(max_length=256)),
                ("to_center", models.CharField(max_length=256)),
                ("booking_datetime", models.DateTimeField()),
                ("consignee", models.CharField(max_length=256)),
                ("current_status", models.CharField(max_length=25)),
                ("status_date", models.DateTimeField()),
                ("tracking_status", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Treacking history",},
        ),
    ]
